3_django/lecture_3/hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("victor", views.victor, name="victor"),
    path("<str:name>", views.greet, name="greet")

]

3_django/lecture_3/lecture_3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls"))
]

3_django/lecture_3/newyear/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("",views.index, name="index")
]

3_django/lecture_3/tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

3_django/lecture_3/hello/models.py
from django.db import models

# Create your models here.

3_django/lecture_3/newyear/models.py
from django.db import models

# Create your models here.

3_django/lecture_3/tasks/models.py
from django.db import models

# Create your models here.

3_django/lecture_3/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def victor(request):
    return HttpResponse("Olá, Victor!!!!!")

def greet(request, name):
    return render(request, "hello/greet.html", {
        "cap_name": name.capitalize()
    })

3_django/lecture_3/newyear/views.py
import datetime
from django.shortcuts import render

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html",{
        "newyear": now.month == 1 and now.day ==1
    })

3_django/lecture_3/tasks/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")

# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []

    return render(request, "tasks/index.html",{
        "tasks": request.session["tasks"]
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data['task']
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "tasks/add.html",{
                "form": form
            })

    return render(request, "tasks/add.html",{
        "form": NewTaskForm()
    })

3_django/lecture_3/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Olá</title>
  </head>
  <body>
    <h1>Olá, {{ cap_name }}!!!!!</h1>
  </body>
</html>

3_django/lecture_3/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Hello!</title>
	</head>
	<body>
		<h1> Olá, Mundo! </h1>
	</body>
</html>

3_django/lecture_3/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Add Task</h1>
    <form action="{% url 'tasks:add' %}" method="post">
      {% csrf_token %}
      {{ form }}
      <input type="submit">
    </form>
    <a href="{% url 'tasks:index' %}">View Tasks</a>
{% endblock%}

3_django/lecture_3/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Tasks</h1>
    <ul>
      {% for task in tasks %}
        <li>{{ task }}</li>
      {% empty %}
        <li>No tasks.</li>
      {% endfor %}
    </ul>
    <a href="{% url 'tasks:add' %}">Add a new Task</a>
{% endblock %}

3_django/lecture_3/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Tasks</title>
  </head>
  <body>
    {% block body %}
    {% endblock %}
  </body>
</html>