project_1/wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/", views.index, name="index"),
    path("wiki/new_page", views.new_page, name="new_page"),
    path("wiki/<str:title>/edit", views.edit, name="edit"),
    path("wiki/<str:title>", views.entry, name="entry")
]

project_1/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

project_1/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

project_1/wiki/encyclopedia/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
import markdown2 
from random import choice

from . import util


def index(request):
    if request.method == "POST":
        return query(request)

    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry(request, title):
    if request.method == "POST":
        return query(request)
    
    entries_list = util.list_entries()

    if title == "random_page":
        entry = choice(entries_list)
        return HttpResponseRedirect(reverse("encyclopedia:entry", args=[entry]))

    elif title in entries_list:
        return render(request, "encyclopedia/entries.html", {
            "title": title,
            "entry": markdown2.markdown(util.get_entry(title)) 
            })
    else:
        return query(request,title)

def query(request,title=None):
    
    if not title:
        title = request.POST["q"]

    entries_list = util.list_entries()
    lower_entries = [x.lower() for x in entries_list]

    if title.lower() in lower_entries:
        index = lower_entries.index(title.lower())
        return HttpResponseRedirect(reverse("encyclopedia:entry", args=[entries_list[index]]))
    else:
        search_list = [ x for x in entries_list if title.lower() in x.lower()]
        return render(request, "encyclopedia/not_found.html", {
            "title": title,
            "search_list": search_list
            })

def new_page(request):
    if request.method == "POST":
        new_title = request.POST["wiki_title"]
        wiki_content = request.POST["wiki_content"]
        entries_list = util.list_entries()
        lower_entries = [x.lower() for x in entries_list]
        
        invalid_titles = ['new_page','random_page']
        if new_title in invalid_titles:
            return render(request, "encyclopedia/new_page.html",{
                "error_message": 'This is not a valid title.',
                "wiki_content": wiki_content,
                "wiki_title": new_title
            })
        elif new_title.lower() in lower_entries:
            index = lower_entries.index(new_title.lower())
            title = entries_list[index]
            error_message = 'There is a current page with this title.'
            sugestion_message = f'You can change the current title or edit the <a href={title}>{title}</a> page.'
            return render(request, "encyclopedia/new_page.html",{
                "error_message": error_message,
                "sugestion_message": sugestion_message,
                "wiki_content": wiki_content,
                "wiki_title": new_title
            })
        else:
            new_file = open(f"entries/{new_title}.md","w")
            new_file.write(wiki_content)
            new_file.close()
            return HttpResponseRedirect(reverse("encyclopedia:entry", args=[new_title]))
    else:
        return render(request, "encyclopedia/new_page.html")

def edit(request, title):
    if request.method == "POST":
        content = request.POST["wiki_content"]
        util.save_entry(title, content)
        return HttpResponseRedirect(reverse("encyclopedia:entry", args=[title]))

    return render(request, "encyclopedia/edit_page.html", {
        "title": title,
        "entry": util.get_entry(title)
        })

project_1/wiki/encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - {{ title }}: edit
{% endblock %}

{% block body %}

<div class="row row_entries">
    <div class="col-sm-8">
        <h1>{{ title }}</h1>
    </div>
</div>

<form method="POST">
    {% csrf_token %}

    <div class="form-group row row_entries">
        <div class="col-sm-10">
            <textarea rows="25" class="form-control" placeholder="Write your content here…" name="wiki_content" id="wiki_content">{{ entry }}</textarea>
        </div>
    </div>
    <div class="form-group row row_entries">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </div>
    
</form>

{% endblock %}

project_1/wiki/encyclopedia/templates/encyclopedia/entries.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - {{ title }}
{% endblock %}

{% block body %}
<div class="row row_entries">
    <div class="col-sm-8">
        <h1>{{ title }}</h1>
    </div>
    <div class="col-sm-2 float-right">
        <a class="btn btn-default btn-lg border"  href="{% url 'encyclopedia:index' %}{{ title }}/edit">
            <span class="fas fa-edit" aria-hidden="true"></span> Edit
        </a>
    </div>
</div>

<div class="row row_entries">
    <div class="col-sm-10">
        {{ entry|safe }}
    </div>
</div>



{% endblock %}

project_1/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <div class="row row_entries">
        <div class="col-sm-8">
            <h1>All Pages</h1>
        </div>
    </div>
    
    <div class="row_entries">
        <ul>
            {% for entry in entries %}
                <li><a href="{% url 'encyclopedia:index' %}{{ entry }}">{{ entry }}</a></li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

project_1/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <div class="row_entries">
                    <form action="{% url 'encyclopedia:index' %}" method="POST">
                        {% csrf_token %}
                        <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                    </form>
                </div>
                <div class="sidebar_options">
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div class="sidebar_options">
                    <a href="{% url 'encyclopedia:new_page' %}">Create New Page</a>
                </div>
                <div class="sidebar_options">
                    <a href="{% url 'encyclopedia:index' %}random_page"">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

project_1/wiki/encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - New page
{% endblock %}

{% block body %}
    <div class="row row_entries">
        <div class="col-sm-8">
            <h1>Create a new page</h1>
        </div>
    </div>

<div class="form-group row">

    <div class="col-sm-1"></div>
    <div class="col-sm-7">

    {% if error_message %}
        <span class="messages error_message">{{ error_message }}</span>
    {% else %}
        &nbsp;
    {% endif %}

    <span class="messages">{{ sugestion_message|safe }}</span>

    </div>
</div>
<form method="POST">
    {% csrf_token %}
    <div class="form-group row">
        <div class="col-sm-1 form-label">
            <label for="wiki_title">Title</label>
        </div>
        <div class="col-sm-7">
            {% if wiki_title %}
                <input class="form-control" value={{wiki_title}} required="required" autofocus="autofocus" placeholder="Page title" type="text" name="wiki_title" id="wiki_title"/>
            {% else %}
                <input class="form-control" value="" required="required" autofocus="autofocus" placeholder="Page title" type="text" name="wiki_title" id="wiki_title"/>
            {% endif %}
        </div>
        <div class="col-sm-4"> 
        </div>
    </div>
    <!--div class="form-group row row_entries">
        <div class="col-sm-1 form-label">
            <label for="wiki_format">Format</label>
        </div>
        <div class="col-sm-7">
            <div class="select-wrapper">
                <select class="form-control select-control" id="wiki_format">
                    <option selected="selected" value="markdown">Markdown</option>
                    <option value="asciidoc">AsciiDoc</option>
                    <option value="rdoc">RDoc</option>
                    <option value="org">Org</option>
                </select>
            </div>
        </div>
        <div class="col-sm-4">
        </div>
    </div-->
    <div class="form-group row">
        <div class="col-sm-1 form-label">
            <label for="wiki_content">Content</label>
        </div>
        <div class="col-sm-7">
            <textarea rows="26" class="form-control" placeholder="Write your content here…" name="wiki_content" id="wiki_content">{% if wiki_content %}{{ wiki_content }}{% endif %}</textarea>
        </div>
        <div class="col-sm-4">
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-1">
            &nbsp;
        </div>
        <div class="col-sm-7">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    
</form>

{% endblock %}

project_1/wiki/encyclopedia/templates/encyclopedia/not_found.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
  Encyclopedia - Not Found!
{% endblock %}

{% block body %}
  <div class="row row_entries">
    <div class="col-sm-8">
      <h1>{{ title }} - Not Found!</h1>
    </div>
  </div>
  
    <div class="row row_entries">
      <div class="col-sm-10 messages">
        The page "<span class="error_message">{{ title }}</span>" does not exist. 
        You are welcome to <a href="{% url 'encyclopedia:new_page' %}">create a new page</a>,
        but consider checking the search results below to see whether the topic is already covered.
      </div>
      <div class="col-sm-2">
      </div>
    </div>

    <div class="row row_entries">
      <div class="col-sm-10">
        <h3>Search results:</h3>
      </div>
    </div>
    <ul>
      {% for entry in search_list %}
        <li><a href="{% url 'encyclopedia:index' %}{{ entry }}">{{ entry }}</a></li>
      {% empty %}
        <li> No results. </li>
      {% endfor %}
    </ul>

{% endblock %}